services:
  keycloak-test-db:
    image: postgres:13
    container_name: keycloak-test-db
    environment:
      POSTGRES_DB: keycloak-test
      POSTGRES_USER: keycloak_user_test
      POSTGRES_PASSWORD: ED1FTMcflyTsj
    networks:
      - keycloak-test-network

  keycloak-test:
    image: quay.io/keycloak/keycloak:18.0.2 
    container_name: keycloak-test
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-test-db/keycloak-test
      KC_DB_USERNAME: keycloak_user_test
      KC_DB_PASSWORD: ED1FTMcflyTsj
      KC_HOSTNAME: keycloak1.local
      KEYCLOAK_FRONTEND_URL: http://localhost:8085
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    networks:
      - keycloak-test-network
    command: start-dev

  nginx-test:
    image: nginx:latest
    container_name: nginx-proxy-test
    volumes:
      - ./configtest/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - proxy-test-network
      - keycloak-test-network

networks:
  proxy-test-network:
  keycloak-test-network:
